modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MC-U-Team/U-Mod/issues"
displayURL="https://u-team.info/mods/umod"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD, MrTroble, Luc_ZZ"

[[mods]]
	modId="umod"
	version="${file.jarVersion}"
	displayName="U Mod"
	updateJSONURL="https://api.u-team.info/update/umod.json"
	description="Everything we wanna have in minecraft :D"
	
	[[dependencies.umod]]
	    modId="forge"
	    mandatory=true
	    versionRange="[31.1.34,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.umod]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.15.2]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.umod]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[2.11.0.156,)"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.umod]]
	    modId="usefulresources"
	    mandatory=true
	    versionRange="[1.0.0.14,)"
	    ordering="NONE"
	    side="BOTH"