modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MC-U-Team/U-Mod/issues"
displayURL="https://u-team.info/mods/umod"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD, Luc_ZZ, MrTroble"

[[mods]]
	modId="umod"
	version="${file.jarVersion}"
	displayName="U Mod"
	updateJSONURL="https://api.u-team.info/update/umod.json"
	description="Everything we wanna have in minecraft :D"
	
	[[dependencies.umod]]
	    modId="forge"
	    mandatory=true
	    versionRange="[28.0.45,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.umod]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.4]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.umod]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[2.7.0.129,)"
	    ordering="NONE"
	    side="BOTH"